---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: 7-demo-source-oci-bb-app
  namespace: flux-system
spec:
  interval: 10s
  provider: generic
  ref:
    tag: 7.7.0-0bb2691
  secretRef:
    name: ghcr-auth
  url: ghcr.io/heinlinaung/bb-app
